### ISSUE TITLE
Exclude option

### ISSUE THREAD

**Issue by johnbot1** [Answers4AWS/backup-monkey#5]
Any chance that you'd consider adding an exclude option? I have many resources in our AWS accounts and need to limit what is being snapped automatically by backup monkey. Being able to point it to a txt file containing ebs id's to exclude would be extremely helpful. 

thanks

**Comment by pas256** [comment]
Sounds like a great idea. Exclude by specific EBS ID, or some tag values (either on the EBS volume or the instance it is attached to).

I'd absolutely accept a PR for that.

**Comment by excessivedemon** [comment]
Hi, I have added this functionality via --tag and --reverse-tags parameters. Please see PR https://github.com/Answers4AWS/backup-monkey/pull/6

**Comment by johnbot1** [comment]
What a surprise, thanks for adding that!

**Comment by pas256** [comment]
Merged as part of #6
